FROM python:3.12-slim

WORKDIR /app

COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ../client/agent_client.py /app/client/

RUN mkdir -p /app/data
ENV VISION_SERVER_URL=http://vision-server:8000
ENV LLM_SERVER_URL=http://llm-server:8001
ENV SEARCH_SERVER_URL=http://search-server:8002
CMD ["python", "/app/client/agent_client.py"]
